"""first vir

Revision ID: 71310d2d790e
Revises: 
Create Date: 2023-07-15 05:10:05.857787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71310d2d790e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
